import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { ConnectButton } from "@rainbow-me/rainbowkit";
import Header from "../components/Header";

export default function Home() {
  return (
    <div
      className={`${styles.container} min-h-screen bg-gradient-to-b from-green-500 to-black`}
    >
      <Head>
        <title>ChainTrust</title>
        <meta name="ChainTrust" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <Header />
      <div className="max-w-xl px-10 py-5 mx-auto text-center text-white">
        <h1 className="mt-4 mb-4 text-3xl font-bold text-black">
          Simplify Your Wealth Management with Digital Trust Funds
        </h1>
        <p className="mb-4 text-lg">
          Leverage the power of blockchain technology to create and manage trust
          funds that are not only more accessible, but also completely
          transparent and secure.
        </p>
        <p className="mt-12 mb-4 text-2xl font-bold text-black">
          How does it work?
        </p>

        <p className="text-lg">
          Each Trust is represented as an NFT with its own wallet address using
          ERC-6551. This allows any assets to be ownable by the NFT which is
          intially owned by the ChainTrust smart contract. Once trust conditions
          are met, the NFT gets transfered to the beneficiary which gives access
          to the linked wallet acccount.
        </p>
        <Link href="/trust">
          <button className="self-center mt-5 text-green-500 transition-colors duration-200 bg-white rounded btn hover:bg-green-500 hover:text-white">
            Get Started
          </button>
        </Link>
      </div>
      <div className="mt-10">
        {/* This could be a section with a few key features of your platform,
            or a few testimonials from your users, for example. */}
      </div>
      <footer className="mt-10">
        {/* This could include contact information, links to your social media profiles,
            or any other information you'd like to include in a footer. */}
      </footer>
    </div>
  );
}

// import Head from "next/head";
// import Link from "next/link";
// import Image from "next/image";
// import styles from "../styles/Home.module.css";
// import { ConnectButton } from "@rainbow-me/rainbowkit";
// import Header from "../components/Header";

// export default function Home() {
//   return (
//     <div
//       className={`${styles.container} min-h-screen bg-gradient-to-b from-blue-500 to-black`}
//     >
//       <Head>
//         <title>ChainTrust</title>
//         <meta name="ChainTrust" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <Header />
//       <div className="max-w-xl px-10 py-5 mx-auto text-center text-white">
//         <h1 className="mb-4 text-4xl font-bold">
//           Revolutionize Your Wealth Management with Digital Trust Funds
//         </h1>
//         <p className="mb-4 text-lg">
//           Welcome to ChainTrust, where we redefine trust and asset management in
//           the digital age. Leverage the power of blockchain technology to create
//           and manage trust funds that are not only more accessible, but also
//           completely transparent and secure.
//         </p>
//         <p className="text-lg">
//           With our platform, you're in full control. The need for a third-party
//           trust is removed, providing you with unprecedented direct access to
//           manage your assets. Embark on your journey towards better financial
//           autonomy with ChainTrust.
//         </p>
//         <Link href="/trust">
//           <button className="self-center text-blue-500 transition-colors duration-200 bg-white btn hover:bg-blue-500 hover:text-white">
//             Get Started
//           </button>
//         </Link>
//       </div>
//     </div>
//   );
// }
